//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SMARTMKT.DL.DATAMODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SMARTMKTEntities : DbContext
    {
        public SMARTMKTEntities()
            : base("name=SMARTMKTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATEGORIA> CATEGORIAs { get; set; }
        public DbSet<GRUPOEDAD> GRUPOEDADs { get; set; }
        public DbSet<PERFIL> PERFILs { get; set; }
        public DbSet<PREGUNTA> PREGUNTAs { get; set; }
        public DbSet<USUARIO> USUARIOs { get; set; }
    
        public virtual ObjectResult<UspObtenerProfesor_Result> UspObtenerProfesor(string uSUARIO1)
        {
            var uSUARIO1Parameter = uSUARIO1 != null ?
                new ObjectParameter("USUARIO1", uSUARIO1) :
                new ObjectParameter("USUARIO1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspObtenerProfesor_Result>("UspObtenerProfesor", uSUARIO1Parameter);
        }
    
        public virtual ObjectResult<UspObtenerUsuario_Result> UspObtenerUsuario(string uSUARIO1)
        {
            var uSUARIO1Parameter = uSUARIO1 != null ?
                new ObjectParameter("USUARIO1", uSUARIO1) :
                new ObjectParameter("USUARIO1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspObtenerUsuario_Result>("UspObtenerUsuario", uSUARIO1Parameter);
        }
    
        public virtual int UspRegistrarUsuario(string uSUARIO, string cONTRASEÑA, string nOMBRE, Nullable<System.DateTime> fECNACIMIENTO, string cORREO)
        {
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cONTRASEÑAParameter = cONTRASEÑA != null ?
                new ObjectParameter("CONTRASEÑA", cONTRASEÑA) :
                new ObjectParameter("CONTRASEÑA", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var fECNACIMIENTOParameter = fECNACIMIENTO.HasValue ?
                new ObjectParameter("FECNACIMIENTO", fECNACIMIENTO) :
                new ObjectParameter("FECNACIMIENTO", typeof(System.DateTime));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspRegistrarUsuario", uSUARIOParameter, cONTRASEÑAParameter, nOMBREParameter, fECNACIMIENTOParameter, cORREOParameter);
        }
    }
}
